// Code generated by Feihan SDK Generator. DO NOT EDIT.
package fhim

import (
	"context"

	fhcore "github.com/feihan-im/openapi-sdk-go/core"
)

// 设置正在输入中（请求）
type CreateTypingReq struct {
	ChatId *string `json:"chat_id,omitempty"` // 聊天 id
}

// 设置正在输入中（响应）
type CreateTypingResp struct {
}

// 设置正在输入中
//
// 设置正在输入中的状态，只持续五秒，仅限私聊
func (impl *v1Chat) CreateTyping(ctx context.Context, req *CreateTypingReq) (*CreateTypingResp, error) {
	apiResp, err := impl.config.ApiClient.Request(ctx, &fhcore.ApiRequest{
		Method: "POST",
		Path:   "/oapi/im/v1/chats/:chat_id/typing",
		Body:   req,
		PathParams: map[string]string{
			"chat_id": stringOrEmpty(req.ChatId),
		},
		WithAppAccessToken: true,
	})
	if err != nil {
		return nil, err
	}
	var resp CreateTypingResp
	if err = apiResp.JSON(&resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// 清除正在输入中（请求）
type DeleteTypingReq struct {
	ChatId *string `json:"chat_id,omitempty"` // 聊天 id
}

// 清除正在输入中（响应）
type DeleteTypingResp struct {
}

// 清除正在输入中
//
// 仅限单聊
func (impl *v1Chat) DeleteTyping(ctx context.Context, req *DeleteTypingReq) (*DeleteTypingResp, error) {
	apiResp, err := impl.config.ApiClient.Request(ctx, &fhcore.ApiRequest{
		Method: "DELETE",
		Path:   "/oapi/im/v1/chats/:chat_id/typing",
		Body:   req,
		PathParams: map[string]string{
			"chat_id": stringOrEmpty(req.ChatId),
		},
		WithAppAccessToken: true,
	})
	if err != nil {
		return nil, err
	}
	var resp DeleteTypingResp
	if err = apiResp.JSON(&resp); err != nil {
		return nil, err
	}
	return &resp, nil
}
