// Code generated by Feihan SDK Generator. DO NOT EDIT.
package fhim

// 消息内容
type MessageContent struct {
	Text              *MessageText              `json:"text,omitempty"`               // 文本消息
	Image             *MessageImage             `json:"image,omitempty"`              // 图片消息
	Sticker           *MessageSticker           `json:"sticker,omitempty"`            // 表情包消息
	Video             *MessageVideo             `json:"video,omitempty"`              // 视频消息
	Audio             *MessageAudio             `json:"audio,omitempty"`              // 语音消息
	File              *MessageFile              `json:"file,omitempty"`               // 文件消息
	UserCard          *MessageUserCard          `json:"user_card,omitempty"`          // 个人名片消息
	GroupCard         *MessageGroupCard         `json:"group_card,omitempty"`         // 群名片消息
	GroupAnnouncement *MessageGroupAnnouncement `json:"group_announcement,omitempty"` // 群公告
}

// 文本消息
type MessageText struct {
	Content         *string                   `json:"content,omitempty"`           // 内容
	AttachmentList  []*MessageTextAttachment  `json:"attachment_list,omitempty"`   // 附件列表，在 content 中的格式为 {{attach:id}}
	MentionUserList []*MessageTextMentionUser `json:"mention_user_list,omitempty"` // 被@人列表，在 content 中的格式为 {{mention:user_id}}，@所有人的 user_id 为 all
	EmojiList       []*MessageTextEmoji       `json:"emoji_list,omitempty"`        // Emoji 列表，在 content 中的格式为 {{emoji:emoji_id}}
}

// 附件
type MessageTextAttachment struct {
	AttachmentId      *string                       `json:"attachment_id,omitempty"`      // 附件 id，在 content 中引用，引用格式为 {{id}}，客户端自定义
	AttachmentType    *string                       `json:"attachment_type,omitempty"`    // 附件类型
	AttachmentContent *MessageTextAttachmentContent `json:"attachment_content,omitempty"` // 附件内容
}

// 附件内容
type MessageTextAttachmentContent struct {
	Image *FileImage `json:"image,omitempty"` // 图片
}

// 图片文件
type FileImage struct {
	Image              *File   `json:"image,omitempty"`                // 大图，宽高最大 1024
	ImageWidth         *uint64 `json:"image_width,omitempty"`          // 图片宽度
	ImageHeight        *uint64 `json:"image_height,omitempty"`         // 图片高度
	ImageOrigin        *File   `json:"image_origin,omitempty"`         // 原图
	ImageOriginWidth   *uint64 `json:"image_origin_width,omitempty"`   // 原图宽度
	ImageOriginHeight  *uint64 `json:"image_origin_height,omitempty"`  // 原图高度
	ImageThumbBytes    []byte  `json:"image_thumb_bytes,omitempty"`    // 缩略图数据，宽高最大 40
	ImageThumbMime     *string `json:"image_thumb_mime,omitempty"`     // 缩略图文件类型
	ImageDominantColor *string `json:"image_dominant_color,omitempty"` // 图片主色调，格式为 #ffffff
}

// 文件
type File struct {
	FileId         *string     `json:"file_id,omitempty"`         // 文件 id
	FileMime       *string     `json:"file_mime,omitempty"`       // 文件类型
	FileSize       *uint64     `json:"file_size,omitempty"`       // 文件大小
	FileEncryption *Encryption `json:"file_encryption,omitempty"` // 文件加密
}

// 加密项
type Encryption struct {
	EncryptionAlgorithm *string `json:"encryption_algorithm,omitempty"` // 加密算法
	EncryptionKey       []byte  `json:"encryption_key,omitempty"`       // 加密密钥
	EncryptedSize       *uint64 `json:"encrypted_size,omitempty"`       // 加密后的大小
}

// @ 用户
type MessageTextMentionUser struct {
	UserId   *UserId `json:"user_id,omitempty"`    // 用户 id
	UserName *string `json:"user_name,omitempty"`  // 当时的用户名称
	IsInChat *bool   `json:"is_in_chat,omitempty"` // 当时该用户是否在聊天中
}

// 用户 id
type UserId struct {
	UserId      *string `json:"user_id,omitempty"`       // 用户在飞函里的 id，同一个用户在所有应用中的 user_id 均相同
	UnionUserId *string `json:"union_user_id,omitempty"` // 用户在同一应用组内的 id，同一个用户在相同应用组下的不同应用中的 union_user_id 均相同
	OpenUserId  *string `json:"open_user_id,omitempty"`  // 用户在应用内的 id，同一个用户在不同应用中的 open_user_id 均不同
}

// Emoji
type MessageTextEmoji struct {
	EmojiId   *string `json:"emoji_id,omitempty"`   // Emoji id
	EmojiName *string `json:"emoji_name,omitempty"` // 当时的 Emoji 名称
}

// 图片消息
type MessageImage struct {
	Image *FileImage `json:"image,omitempty"` // 图片
}

// 表情包消息
type MessageSticker struct {
	Sticker *Sticker `json:"sticker,omitempty"` // 表情包
}

// 表情包
type Sticker struct {
	StickerId       *string           `json:"sticker_id,omitempty"`        // 表情包 id
	StickerName     *string           `json:"sticker_name,omitempty"`      // 表情包名称
	StickerNameI18n map[string]string `json:"sticker_name_i18n,omitempty"` // 表情包名称国际化
	StickerImage    *FileImage        `json:"sticker_image,omitempty"`     // 表情包图片
}

// 视频消息
type MessageVideo struct {
	Video *FileVideo `json:"video,omitempty"` // 视频
}

// 视频文件
type FileVideo struct {
	Video         *File      `json:"video,omitempty"`          // 视频
	VideoWidth    *uint64    `json:"video_width,omitempty"`    // 视频宽度
	VideoHeight   *uint64    `json:"video_height,omitempty"`   // 视频高度
	VideoDuration *float64   `json:"video_duration,omitempty"` // 视频时长
	VideoPreview  *FileImage `json:"video_preview,omitempty"`  // 视频预览图
}

// 语音消息
type MessageAudio struct {
	Audio *FileAudio `json:"audio,omitempty"` // 音频
}

// 音频文件
type FileAudio struct {
	Audio         *File    `json:"audio,omitempty"`          // 音频
	AudioDuration *float64 `json:"audio_duration,omitempty"` // 音频时长
}

// 文件消息
type MessageFile struct {
	File     *File   `json:"file,omitempty"`     // 文件
	Filename *string `json:"filename,omitempty"` // 文件名
}

// 个人名片消息
type MessageUserCard struct {
	UserId *UserId `json:"user_id,omitempty"` // 用户 id
}

// 群名片消息
type MessageGroupCard struct {
	ChatId *string `json:"chat_id,omitempty"` // 聊天 id
}

// 群公告
type MessageGroupAnnouncement struct {
	MessageText *MessageText `json:"message_text,omitempty"` // 公告内容
}

// 消息
type Message struct {
	MessageId        *string           `json:"message_id,omitempty"`         // 消息 id
	MessageType      *string           `json:"message_type,omitempty"`       // 消息类型
	MessageStatus    *string           `json:"message_status,omitempty"`     // 消息状态
	MessageContent   *MessageContent   `json:"message_content,omitempty"`    // 消息内容
	MessageCreatedAt *uint64           `json:"message_created_at,omitempty"` // 消息创建时间（毫秒）
	ChatId           *string           `json:"chat_id,omitempty"`            // 聊天 id
	ChatSeqId        *uint64           `json:"chat_seq_id,omitempty"`        // 服务端生成的聊天级别的消息趋势递增 id，用于单链排序
	SenderId         *UserId           `json:"sender_id,omitempty"`          // 发送者 id
	Reply            *MessagePropReply `json:"reply,omitempty"`              // 回复属性
}

// 消息回复属性
type MessagePropReply struct {
	ReplyMessageId *string `json:"reply_message_id,omitempty"` // 本条消息回复的消息 id
}
