// Code generated by Feihan SDK Generator. DO NOT EDIT.
package fhim

import (
	fhcore "github.com/feihan-im/openapi-sdk-go/core"
)

type V1 struct {
	Chat    *v1Chat
	Message *v1Message
}

func New(config *fhcore.Config) *V1 {
	return &V1{
		Chat:    &v1Chat{config: config},
		Message: &v1Message{config: config, Event: &v1MessageEvent{config: config}},
	}
}

func stringOrEmpty(s *string) string {
	if s == nil {
		return ""
	}
	return *s
}
