name: Go
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - 'feat-**'

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: ['1.12', '1.x']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      
      - name: Lint package
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
